### ISSUE TITLE
document on features needed for the livechat

### ISSUE THREAD

**Issue by Hubert-Vecchioli** [The-AJE-Alliance/ft_transcendence#57]
- daphne
- django channels (websocket)
- djangorest

**Comment by mortebrume** [comment]
use rabbitmq instead of django channels for the queue management

**Comment by Hubert-Vecchioli** [comment]
WORK IN PROGRESS 

# Reminder of the requirements
◦ The user should be able to send direct messages to other users.
◦ The user should be able to block other users. This way, they will see no more
messages from the account they blocked.
◦ The user should be able to invite other users to play a Pong game through the
chat interface.
◦ The tournament system should be able to warn users expected for the next
game.
◦ The user should be able to access other players profiles through the chat interface

# Proposed Live chat actions to implement
## Required to meet the need of the subject
### 1/ Initiate the chat when a user logs in
![Image](https://github.com/user-attachments/assets/34248429-32e3-4f37-b333-11c01c608d30)

**APIs needed**
From (micro service) | To (microservice) | Method | What
-- | -- | -- | --
Authentification | LiveChat | POST | User logged in
LiveChat | ? | Get | Get User data

**Internal logic needed**
- Trigger a GET when a POST is received by the Authentification
- Trigger N GET for its friend 




## Improvements to implement
◦ Add a red dot to indicate an unread message in the live chat 


# Proposed Live chat models to support those actions
### Users
Variables | Types
-- | --
Import of Users from another microservice |  

### Conversations
Variables | Types
-- | --
user1 | Foreign Key
user2 | Foreign Key
created_at | Timestamp
isBlockedByUser1 | Boolean
isBlockedByUser2 | Boolean
hasUnreadMessagesByUser1 | Boolean
hasUnreadMessagesByUser2 | Boolean

Note: We enforce a unicity of the pair (user1, user2), regardless of its order in the pair

### Messages
Variables | Types
-- | --
conversation_id | Foreign Key
sentFromUser_id | Foreign Key
messageContent | CharField
created_at | Timestamp
